name: Move Project Task to Needs Review

on:
  pull_request:
    types:
      - opened

jobs:
  move-task:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Move project task to Needs Review
        env:
          GH_TOKEN: ${{ secrets.PAT_GITHUB }}  # Set GH_TOKEN for GitHub CLI
        run: |
          # Define variables
          PR_NUMBER=$(jq -r .number < "${GITHUB_EVENT_PATH}")
          REPO_FULL_NAME=${{ github.repository }}
          
          # Get linked project cards
          PROJECT_ITEM_ID=$(gh api graphql -F prNumber="$PR_NUMBER" -F repo="$REPO_FULL_NAME" -F owner="${{ github.repository_owner }}" -f query='
            query($prNumber: Int!, $repo: String!, $owner: String!) {
              repository(name: $repo, owner: $owner) {
                pullRequest(number: $prNumber) {
                  projectItems(first: 1) {
                    nodes {
                      id
                    }
                  }
                }
              }
            }
          ' --jq '.data.repository.pullRequest.projectItems.nodes[0].id')

          # Exit if no project is linked
          if [ -z "$PROJECT_ITEM_ID" ]; then
            echo "No linked project task found for this pull request."
            exit 0
          fi

          # Find the Needs Review column ID
          COLUMN_ID=$(gh api graphql -F owner="${{ github.repository_owner }}" -F repo="$REPO_FULL_NAME" -f query='
            query($owner: String!, $repo: String!) {
              user(login: $owner) {
                projects(first: 10) {
                  nodes {
                    columns(first: 10) {
                      nodes {
                        id
                        name
                      }
                    }
                  }
                }
              }
            }
          ' --jq '.data.user.projects.nodes[].columns.nodes[] | select(.name == "Needs Review") | .id')

          if [ -z "$COLUMN_ID" ]; then
            echo "Could not find 'Needs Review' column."
            exit 1
          fi

          # Move the task to Needs Review
          gh api graphql -F itemId="$PROJECT_ITEM_ID" -F columnId="$COLUMN_ID" -f query='
            mutation($itemId: ID!, $columnId: ID!) {
              moveProjectCard(input: {cardId: $itemId, columnId: $columnId}) {
                card {
                  id
                }
              }
            }
          '
